id: io.github.Sunderland93.sway-input-config
runtime: org.kde.Platform
runtime-version: '5.15-22.08'
sdk: org.kde.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm15
command: sway-input-config
rename-desktop-file: sway-input-config.desktop
rename-icon: sway-input-config
finish-args:
- "--socket=wayland"
- "--device=dri"
- "--filesystem=/run/user:ro"
- "--filesystem=xdg-config/sway"
modules:
- name: python3-appdirs
  buildsystem: simple
  build-commands:
   - pip3 install --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} appdirs
  sources:
  - type: file
    url: https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
    sha256: a841dacd6b99318a741b166adb07e19ee71a274450e68237b4650ca1055ab128
- name: python3-i3ipc
  buildsystem: simple
  build-commands:
   - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} i3ipc
  sources:
  - type: file
    url: https://files.pythonhosted.org/packages/de/30/294b07ddeccb58855c890c3ef3a951c3b0c1e2d089666d548b6a9edc39fb/i3ipc-2.2.1-py3-none-any.whl
    sha256: c0b898223d50d42c90c818deb5033d1304c582755547dee7d15df3e3781bc690
  - type: file
    url: https://files.pythonhosted.org/packages/fc/b8/ff33610932e0ee81ae7f1269c890f697d56ff74b9f5b2ee5d9b7fa2c5355/python_xlib-0.33-py2.py3-none-any.whl
    sha256: c3534038d42e0df2f1392a1b30a15a4ff5fdc2b86cfa94f072bf11b10a164398
- name: pyside2
  build-options:
     prepend-path: /usr/lib/sdk/llvm15/bin
     prepend-ld-library-path: /usr/lib/sdk/llvm11/lib
  buildsystem: cmake-ninja
  builddir: true
  config-opts:
     - -DCMAKE_BUILD_TYPE=RelWithDebInfo
     - -DUSE_PYTHON_VERSION=3
     - -DBUILD_TESTS=OFF
  post-install:
    - |
      # Make package discoverable by setuptools
      printf "Metadata-Version: 1.0\nName: PySide2\nVersion: %s\n" \
      "$(python3 -c "import PySide2; print(PySide2.__version__)")" \
      > "$(dirname "$(python3 -c "import PySide2; print(PySide2.__file__)")")/../pyside2.egg-info"
  cleanup:
    - /qt5include
    - /bin
  sources:
   - type: archive
     url: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.15.10-src/pyside-setup-opensource-src-5.15.10.tar.xz
     sha256: 2af691d3613a41f83a60439b46568fc2c696dbfae42f7cd7b07152d115ead33a
   - type: shell
     commands:
     - mkdir -p /app/qt5include && cp -R /usr/include/Qt* /app/qt5include # https://bugreports.qt.io/browse/PYSIDE-787
     - sed -i 's|\(--include-paths=\)|\1/app/qt5include:|' sources/pyside2/cmake/Macros/PySideModules.cmake
   - type: patch
     path: fix-GLES-builds.patch
- name: sway-input-config
  buildsystem: simple
  build-commands:
   - pip3 install --prefix=/app --no-deps .
  sources:
   - type: archive
     url: https://github.com/Sunderland93/sway-input-config/archive/refs/tags/v1.3.2.2.tar.gz
     sha256: dbded64ea12485af1a0cccf211b3716e84fe25393c84b24178af23b611d82f66
